---
- name: Install Docker, Docker Compose & Prerequisites
  hosts: linux_servers
  become: true
  roles:
    - docker

- name: Phase 1 - Initial Setup with HTTP only
  import_playbook: phase1_init.yml

- name: Phase 2 - Certificate Generation and HTTPS Setup
  import_playbook: phase2_ssl.yml

- name: Phase 3 - Verification of HTTPS Setup on local machine
  import_playbook: verification_state.yml
